-- Generated by HyprMod

-- Settings
hl.config({
    input = {
        kb_layout = "fr",
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "0x0",
    scale = 1.2,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + ampersand")
hl.bind("SUPER + ampersand", hl.dsp.focus({ workspace = 1 }))
hl.unbind("SUPER + SHIFT + ampersand")
hl.bind("SUPER + SHIFT + ampersand", hl.dsp.window.move({ workspace = 1 }))
hl.unbind("SUPER + apostrophe")
hl.bind("SUPER + apostrophe", hl.dsp.focus({ workspace = 4 }))
